services:
  mysql:
    platform: linux/x86_64
    image: mysql:5.7
    volumes:
      - mysql-data:/var/lib/mysql
    ports:
      - ${MYSQL_PORT:-3306}:3306
    environment:
      - MYSQL_ROOT_PASSWORD=password

  postgresql:
    image: postgres:latest
    volumes:
      - postgresql-data:/var/lib/postgresql/data
    ports:
      - ${POSTGRESQL_PORT:-5432}:5432
    environment:
      - POSTGRES_PASSWORD=password

  app:
    build:
      context: .
    environment:
      DB_HOST: mysql
      AR_VERSION: 7.0
    volumes:
      - .:/usr/src/app
    depends_on:
      - mysql
      - postgresql
    command: tail -f /dev/null

volumes:
  mysql-data:
  postgresql-data:
